import {
    Endpoint,
    Host,
    Prisma,
    Project,
    RepeaterMetadata,
    Transaction,
    TransactionBody,
    TransactionHeader,
} from '@prisma/client'

// Database model types (generated by Prisma)
export type {
    Project,
    Transaction,
    TransactionHeader,
    TransactionBody,
    RepeaterMetadata,
    SystemConfig,
    Host,
    Endpoint,
    PrismaClient,
} from '@prisma/client'

// Repository input types
// Prisma input types
export type ProjectCreateInput = Prisma.ProjectCreateInput
export type ProjectUpdateInput = Prisma.ProjectUpdateInput
export type ProjectFindManyArgs = Prisma.ProjectFindManyArgs

export type TransactionCreateInput = Prisma.TransactionCreateInput
export type TransactionUpdateInput = Prisma.TransactionUpdateInput
export type TransactionFindManyArgs = Prisma.TransactionFindManyArgs

export type HostCreateInput = Prisma.HostCreateInput
export type HostUpdateInput = Prisma.HostUpdateInput
export type HostFindManyArgs = Prisma.HostFindManyArgs

export type EndpointCreateInput = Prisma.EndpointCreateInput
export type EndpointUpdateInput = Prisma.EndpointUpdateInput
export type EndpointFindManyArgs = Prisma.EndpointFindManyArgs

export type SystemConfigCreateInput = Prisma.SystemConfigCreateInput
export type SystemConfigUpdateInput = Prisma.SystemConfigUpdateInput
export type SystemConfigFindManyArgs = Prisma.SystemConfigFindManyArgs

export type JsonObject = Prisma.JsonObject

export type ParsedProject = Omit<Project, 'settings'> & {
    settings: ProjectSettings
}

export interface ProjectSettings {
    maxTransactions?: number
    retentionDays?: number
    hostFilterMode?: 'blacklist' | 'whitelist'
    hostFilter?: string[]
    maxBodySize?: number
}

// Extended types for complex queries
export interface TransactionWithHeaders extends Transaction {
    requestHeaders: TransactionHeader[]
    responseHeaders: TransactionHeader[]
    requestBody?: TransactionBody
    responseBody?: TransactionBody
    repeaterMeta?: RepeaterMetadata
}

export interface ProjectWithStats extends Project {
    _count?: {
        transactions: number
    }
    _sum?: {
        transactions: {
            requestSize: number
            responseSize: number
        }
    }
}

export interface HostWithEndpoints extends Host {
    endpoints: Endpoint[]
}

// Service layer types
export interface DatabaseServiceOptions {
    databaseUrl?: string
    logLevel?: 'info' | 'warn' | 'error'
}

export interface ProjectStats {
    transactionCount: number
    totalSize: number
    lastActivity: Date | null
}
