import type {
    Prisma,
    Project as DatabaseProject,
    Transaction,
    TransactionBody,
    TransactionHeader,
} from '@prisma/client'

// Database model types (generated by Prisma)
export type {
    Project as DatabaseProject,
    Transaction,
    TransactionHeader,
    TransactionBody,
    SystemConfig,
    Host,
    Endpoint,
    PrismaClient,
} from '@prisma/client'

// Repository input types
// Prisma input types
export type ProjectCreateInput = Prisma.ProjectCreateInput
export type ProjectUpdateInput = Prisma.ProjectUpdateInput
export type ProjectFindManyArgs = Prisma.ProjectFindManyArgs

export type TransactionCreateInput = Prisma.TransactionCreateInput
export type TransactionUpdateInput = Prisma.TransactionUpdateInput
export type TransactionFindManyArgs = Prisma.TransactionFindManyArgs

export type HostCreateInput = Prisma.HostCreateInput
export type HostUpdateInput = Prisma.HostUpdateInput
export type HostFindManyArgs = Prisma.HostFindManyArgs

export type EndpointCreateInput = Prisma.EndpointCreateInput
export type EndpointUpdateInput = Prisma.EndpointUpdateInput
export type EndpointFindManyArgs = Prisma.EndpointFindManyArgs

export type SystemConfigCreateInput = Prisma.SystemConfigCreateInput
export type SystemConfigUpdateInput = Prisma.SystemConfigUpdateInput
export type SystemConfigFindManyArgs = Prisma.SystemConfigFindManyArgs

export type JsonObject = Prisma.JsonObject

export type Project = Omit<DatabaseProject, 'settings' | 'tags'> & {
    settings: ProjectSettings
    tags: string[]
}

export interface ProjectSettings {
    maxTransactions?: number
    retentionDays?: number
    hostFilterMode?: 'blacklist' | 'whitelist'
    hostFilter?: string[]
    maxBodySize?: number
}

// Extended types for complex queries
export interface FullTransaction extends Transaction {
    requestHeaders: TransactionHeader[]
    responseHeaders: TransactionHeader[]
    requestBody: TransactionBody | null
    responseBody: TransactionBody | null
}

export interface ProjectWithStats extends DatabaseProject {
    _count?: {
        transactions: number
    }
    _sum?: {
        transactions: {
            requestSize: number
            responseSize: number
        }
    }
}

// Service layer types
export interface DatabaseServiceOptions {
    databaseUrl?: string
    logLevel?: 'info' | 'warn' | 'error'
}

export interface ProjectStats {
    transactionCount: number
    totalSize: number
    lastActivity: Date | null
}
