import type { Prisma } from '@prisma/client'

// Database model types (generated by Prisma)
export type { SystemConfig, Host, Endpoint, PrismaClient } from '@prisma/client'

export type HostCreateInput = Prisma.HostCreateInput
export type HostUpdateInput = Prisma.HostUpdateInput
export type HostFindManyArgs = Prisma.HostFindManyArgs

export type EndpointCreateInput = Prisma.EndpointCreateInput
export type EndpointUpdateInput = Prisma.EndpointUpdateInput
export type EndpointFindManyArgs = Prisma.EndpointFindManyArgs

export type SystemConfigCreateInput = Prisma.SystemConfigCreateInput
export type SystemConfigUpdateInput = Prisma.SystemConfigUpdateInput
export type SystemConfigFindManyArgs = Prisma.SystemConfigFindManyArgs

export type JsonObject = Prisma.JsonObject

export * from './transaction'
export * from './project'
export * from './auth'
