/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    BodyViewer: typeof import('./src/components/BodyViewer.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CollapsibleSection: typeof import('./src/components/CollapsibleSection.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DesignSystemDemo: typeof import('./src/components/DesignSystemDemo.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    HeadersList: typeof import('./src/components/HeadersList.vue')['default']
    HostsSidebar: typeof import('./src/components/HostsSidebar.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RequestPanel: typeof import('./src/components/RequestPanel.vue')['default']
    RequestResponseViewer: typeof import('./src/components/RequestResponseViewer.vue')['default']
    ResponsePanel: typeof import('./src/components/ResponsePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TrafficEntry: typeof import('./src/components/TrafficEntry.vue')['default']
    TrafficHeader: typeof import('./src/components/TrafficHeader.vue')['default']
    TrafficList: typeof import('./src/components/TrafficList.vue')['default']
  }
}
