/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BodyViewer: typeof import('./src/components/BodyViewer.vue')['default']
    CollapsibleSection: typeof import('./src/components/CollapsibleSection.vue')['default']
    HeadersList: typeof import('./src/components/HeadersList.vue')['default']
    HostsSidebar: typeof import('./src/components/HostsSidebar.vue')['default']
    RequestPanel: typeof import('./src/components/RequestPanel.vue')['default']
    RequestResponseViewer: typeof import('./src/components/RequestResponseViewer.vue')['default']
    ResponsePanel: typeof import('./src/components/ResponsePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TrafficEntry: typeof import('./src/components/TrafficEntry.vue')['default']
    TrafficHeader: typeof import('./src/components/TrafficHeader.vue')['default']
    TrafficList: typeof import('./src/components/TrafficList.vue')['default']
  }
}
